# Generated by Django 3.2.3 on 2021-05-16 15:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(help_text='The password to show at the end of the map.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('question', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('answer', models.CharField(max_length=200)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.PositiveIntegerField(help_text='The stages are sorted by their level, so the level with the next higher number will be the next question. First question is the lowest index.')),
                ('corresponding_map', models.ForeignKey(help_text='The corresponding map.', on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='hunting.map')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
    ]
