# Generated by Django 3.2.2 on 2021-05-12 09:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('password', models.CharField(help_text='The password to show at the end of the map.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('question', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('answer', models.CharField(max_length=200)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corresponding_map', models.ForeignKey(help_text='The corresponding map.', on_delete=django.db.models.deletion.PROTECT, to='hunting.map')),
                ('next_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hunting.stage')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='first_stage',
            field=models.ForeignKey(blank=True, help_text='This field has to be set but can be skipped at the beginning if the first stage was not created.', null=True, on_delete=django.db.models.deletion.CASCADE, to='hunting.stage'),
        ),
    ]
